#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Enable MCUboot bootloader
CONFIG_BOOTLOADER_MCUBOOT=y

# Enable BLE OTA DFU
CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU=y
